# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.8.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "d4e6b95c12a08b4de2d48b45d5b4d594e5d32fab"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
