kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - /choerodon-agent
        - --v={{ .Values.config.logLevel }}
        - --host=tiller-deploy.kube-system:44134
        - --tiller-connection-timeout={{ .Values.config.tillerConnectionTimeout }}
        - --connect={{ .Values.config.connect }}?version={{ .Chart.Version }}&envId={{ .Values.config.envId }}&key=env:{{ .Release.Namespace }}.envId:{{.Values.config.envId}}
        - --token={{ .Values.config.token }}
        - --namespace={{ .Release.Namespace }}
        - --agent-version={{ .Chart.Version }}
        - --envId={{ .Values.config.envId }}
      {{- range $key, $value := .Values.config.extraArgs }}
        - --{{ $key }}={{ $value }}
      {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.config.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: {{ if .Values.rbac.create }}"{{ .Release.Name }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      terminationGracePeriodSeconds: 30
  revisionHistoryLimit: 3
  minReadySeconds: 0
