kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  annotations:
{{ include "service.annotations.standard" . | indent 4 }}
  name: {{ .Release.Name }}
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "service.match.labels" . | indent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "service.labels.standard" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - /choerodon-agent
        - --v={{ .Values.config.logLevel }}
        - --host=tiller-deploy.kube-system:44134
        - --tiller-connection-timeout={{ .Values.config.tillerConnectionTimeout }}
        - --connect={{ .Values.config.connect }}?version={{ .Chart.Version }}&envId={{ .Values.config.envId }}&key=env:{{ .Release.Namespace }}
        - --token={{ .Values.config.token }}
        - --namespace={{ .Release.Namespace }}
        ports:
        - name: http
          containerPort: {{ .Values.config.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: 30
  revisionHistoryLimit: 3
  minReadySeconds: 0
