kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "service.labels.standard" . | indent 4 }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
