apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: c7nhelmreleases.choerodon.io
spec:
  group: choerodon.io
  names:
    kind: C7NHelmRelease
    listKind: C7NHelmReleaseList
    plural: c7nhelmreleases
    singular: c7nhelmrelease
  scope: Namespaced
  version: v1alpha1
